version: '3'
services:
  project1:
    build: ./Candidate
    ports:
      - "8090:8080" # Map container port 80 to host port 8080

  project2:
    build: ./Co-share-ms-mouhib
    ports:
      - "8081:8080" # Map container port 80 to host port 8081
