version: '3'
services:
  project1:
    build: ./ProductMicroService
    ports:
      - "8090:8080" # Map container port 80 to host port 8080

  project2:
    build: ./OfferMicroService
    ports:
      - "8081:8080" # Map container port 80 to host port 8081
